# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14fxXguhKsU4d_am8_cEUlCzTX3Yar6ID

#Phase 3 :
#Classification:
"""

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import ConfusionMatrixDisplay

"""# Information Gain (entropy):
Splitting Data into: 70% Training and 30% Test

"""

#Create decision tree classifer object:
clf_entropy = DecisionTreeClassifier(criterion='entropy')

#Train decision tree classifer
clf_entropy= clf_entropy.fit(X_train, y_train)

#Predict the response for test dataset
y_pred_entropy = clf.predict (X_test)

"""# confusion matrix:

"""

# Compute and print the confusion matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

    disp = ConfusionMatrixDisplay(confusion_matrix=cm)
    disp.plot()
    plt.title(f'Confusion Matrix - Test Size: {test_size} - Entropy')
    plt.show()